Portafolio/Areas/Admin/Controllers/TareaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portafolio.Datos.Repository.IRepository;
using Portafolio.Modelos;
using Portafolio.Modelos.ViewModels;
using System.Linq;

namespace Portafolio.Areas.Admin.Controllers
{
    [Area("Admin")]
        public class TareaController : Controller
        {
            private readonly IUnitOfWork _unitOfWork;

            public TareaController(IUnitOfWork unitOfWork)
            {
                _unitOfWork = unitOfWork;
            }

            public IActionResult Index()
            {
                return View();
            }

            public IActionResult Upsert(int? id)
            {
                TareaVM tareaVM = new TareaVM()

                {
                    Tarea = new Tarea(),
                    FlujoTareaList = _unitOfWork.FlujoTarea.GetAll().Select(i => new SelectListItem
                    {
                        Text = i.Nom_flujo,
                        Value = i.Id.ToString()

                    })
                };

                if (id == null)
                {
                    //this is for create
                    return View(tareaVM);
                }
                //this is for edit
                tareaVM.Tarea = _unitOfWork.Tarea.Get(id.GetValueOrDefault());
                if (tareaVM.Tarea == null)
                {
                    return NotFound();
                }
                return View(tareaVM);

            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Upsert(TareaVM tareaVM)
            {
                if (ModelState.IsValid)
                {
                    if (tareaVM.Tarea.Id != 0)
                    {
                        Tarea objFromDb = _unitOfWork.Tarea.Get(tareaVM.Tarea.Id);

                    }


                    if (tareaVM.Tarea.Id == 0)
                    {
                        _unitOfWork.Tarea.Add(tareaVM.Tarea);


                    }

                    else

                    {
                        _unitOfWork.Tarea.Update(tareaVM.Tarea);

                    }

                    _unitOfWork.Save();
                    return RedirectToAction(nameof(Index));


                }
                else

                {
                    tareaVM.FlujoTareaList = _unitOfWork.FlujoTarea.GetAll().Select(i => new SelectListItem
                    {
                        Text = i.Nom_flujo,
                        Value = i.Id.ToString()

                    });

                    if (tareaVM.Tarea.Id != 0)
                    {
                        tareaVM.Tarea = _unitOfWork.Tarea.Get(tareaVM.Tarea.Id);

                    }
                }

                return View(tareaVM);
            }

            #region API CALLS

            [HttpGet]
            public IActionResult GetAll()
            {
                var allObj = _unitOfWork.Tarea.GetAll(includeProperties: "FlujoTarea");
                return Json(new { data = allObj });
            }

            [HttpDelete]
            public IActionResult Delete(int id)
            {
                var objFromDb = _unitOfWork.Tarea.Get(id);
                if (objFromDb == null)
                {
                    return Json(new { success = false, message = "Error en el eliminación" });
                }
                _unitOfWork.Tarea.Remove(objFromDb);
                _unitOfWork.Save();
                return Json(new { success = true, message = "Eliminación exitosa" });

            }
        }
    }

    #endregion

Portafolio/Areas/Admin/Controllers/TipoFlujoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Portafolio.Datos.Repository.IRepository;
using Portafolio.Modelos;

namespace Portafolio.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TipoFlujoController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TipoFlujoController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            TipoFlujo tipoFlujo = new TipoFlujo();
            if (id == null)
            {
                //this is for create
                return View(tipoFlujo);
            }
            //this is for edit
            tipoFlujo = _unitOfWork.TipoFlujo.Get(id.GetValueOrDefault());
            if (tipoFlujo == null)
            {
                return NotFound();
            }
            return View(tipoFlujo);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(TipoFlujo tipoFlujo)
        {
            if (ModelState.IsValid)
            {
                if (tipoFlujo.Id == 0)
                {
                    _unitOfWork.TipoFlujo.Add(tipoFlujo);
                    
                }
                else
                {
                    _unitOfWork.TipoFlujo.Update(tipoFlujo);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoFlujo);
        }


        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.TipoFlujo.GetAll();
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.TipoFlujo.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error en el eliminación" });
            }
            _unitOfWork.TipoFlujo.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Eliminación exitosa" });

        }

        #endregion
    }
}

Portafolio/Areas/Admin/Controllers/UnidadInternaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Portafolio.Datos.Repository.IRepository;
using Portafolio.Modelos;

namespace Portafolio.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UnidadInternaController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public UnidadInternaController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            UnidadInterna unidadInterna = new UnidadInterna();
            if (id == null)
            {
                //this is for create
                return View(unidadInterna);
            }
            //this is for edit
            unidadInterna = _unitOfWork.UnidadInterna.Get(id.GetValueOrDefault());
            if (unidadInterna == null)
            {
                return NotFound();
            }
            return View(unidadInterna);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(UnidadInterna unidadInterna)
        {
            if (ModelState.IsValid)
            {
                if (unidadInterna.Id == 0)
                {
                    _unitOfWork.UnidadInterna.Add(unidadInterna);
                    
                }
                else
                {
                    _unitOfWork.UnidadInterna.Update(unidadInterna);
                }
                _unitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(unidadInterna);
        }


        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {
            var allObj = _unitOfWork.UnidadInterna.GetAll();
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDb = _unitOfWork.UnidadInterna.Get(id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error en el eliminación" });
            }
            _unitOfWork.UnidadInterna.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Eliminación exitosa" });

        }

        #endregion
    }
}

Portafolio/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Portafolio.Datos.Repository.IRepository;
using Portafolio.Modelos;
using Portafolio.Modelos.ViewModels;
using Microsoft.EntityFrameworkCore;
using Portafolio.Datos.Data;
using Microsoft.VisualStudio.Web.CodeGeneration.Contracts.Messaging;

namespace Portafolio.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

       

        #region API CALLS

       [HttpGet]
       public IActionResult GetAll()
       {
            var userList = _db.ApplicationUsers.Include(u =>u.UnidadInterna).ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();

            foreach(var user in userList)
            {
                var roleId = userRole.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(u => u.Id == roleId).Name;
                if (user.UnidadInterna == null)
                {
                    user.UnidadInterna = new UnidadInterna()
                    {
                        Des_unidad = ""
                    };

                }

            }

            return Json(new{ data = userList });


       }

        [HttpPost]
        public IActionResult LockUnlock ([FromBody] string id)
        {
            var objFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == id);
            if(objFromDb == null)
            {
                return Json(new { success = false, message = "Error en Bloqueo/Desbloqueo" });
            }
            if(objFromDb.LockoutEnd!=null && objFromDb.LockoutEnd > DateTime.Now)
            {
                //usuario esta bloqueado, vamos a desbloquearlo ahorita we
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            _db.SaveChanges();
            return Json(new { success = true, message = "Todo nice" });

        }

        #endregion
    }

}

Portafolio/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Crear</button>
    </div>
    <div class="col">
        <a asp-action="Index"  class="btn btn-success form-control">Volver</a>
    </div>
</div>

Portafolio/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Actualizar</button>
    </div>
    <div class="col">
        <a asp-action="Index"  class="btn btn-success form-control">Volver</a>
    </div>
</div>

Portafolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Process SA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Process SA</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                CRUD Admin
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="TipoFlujo" asp-action="Index">Tipos de flujo</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="UnidadInterna" asp-action="Index">Unidad interna</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="FlujoTarea" asp-action="Index">Flujos de Tareas</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Usuarios/Tareas
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Usuarios</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Tarea" asp-action="Index">Tareas</a>

                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white-50 bg-primary">
        <div class="container ">
            &copy; 2020 - Process SA
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>